name: Terraform Apply

on:
  push:
    branches:
      - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.2

    - name: Terraform Init
      run: terraform init -backend-config="password=$TF_HTTP_PASSWORD"
      env:
        TF_HTTP_PASSWORD: ${{ secrets.TOKEN }}

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan Destroy
      run: terraform plan -destroy
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Manual Intervention step
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        timeout-minutes: 60

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

