name: Terraform Plan

on:
  push:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.2  # Use the appropriate Terraform version

#    - name: TFstate.dev Backend Config
#      shell: bash
#      run: export TF_HTTP_PASSWORD="${{ secrets.TOKEN }}"

    - name: Terraform Init
      run: terraform init
      env:
        TF_HTTP_PASSWORD: ${{ secrets.TOKEN }}

    - name: Terraform Plan
      run: terraform plan
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
